### ISSUE TITLE
specifying quantile

### ISSUE THREAD

**Issue by amoreirapass** [sdpython/mlinsights#11]
Hi!

I was wondering if there is a way of specifying the quantile of interest (95%, 5%, or any other...) to be used in the quantile regression code as an input variable. Also, currently, what is the equivalent default quantile? 
Maybe I am seeing it wrong, because according to the specifications, you are using the Iteratively reweighted least squares, which may have a different loss function formulation. 

Many thanks.

**Comment by sdpython** [comment]
The default quantile is actually 50%. I'll looking into a way to specify it.

**Comment by sdpython** [comment]
I released the package on pypi.

https://pypi.org/project/mlinsights/

Xavier

**Comment by amoreirapass** [comment]
Thank you, Xavier.
