### ISSUE TITLE
Import-issue in Predictable t-SNE

### ISSUE THREAD

**Issue by Nick18899** [sdpython/mlinsights#119]
After trying to use such code:
`from mlinsights.mlmodel import PredictableTSNE`
I got this error:

> [/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_bagging.py](https://localhost:8080/#) in <module>
>      14 import numpy as np
>      15 
> ---> 16 from ..base import ClassifierMixin, RegressorMixin, _fit_context
>      17 from ..metrics import accuracy_score, r2_score
>      18 from ..tree import DecisionTreeClassifier, DecisionTreeRegressor
> 
> ImportError: cannot import name '_fit_context' from 'sklearn.base' (/usr/local/lib/python3.10/dist-packages/sklearn/base.py)

**Comment by sdpython** [comment]
Which version of scikit-learn are you using? I'm currently refactoring the package. This should be fixed soon.

**Comment by xadupre** [comment]
I just released a new verions. I'll close the issue. Feel free to reopen it.
