### ISSUE TITLE
Optimal decission tree for piecewise estimator

### ISSUE THREAD

**Issue by m0wer** [sdpython/mlinsights#72]
In [piecewise_estimator.py](../tree/master/mlinsights/mlmodel/piecewise_estimator.py) the *binner* is trainned independently from the *estimator*.

For example the `DecissionTreeRegressor` from sklearn is going to decide the splits minimizing the MSE (by default) which will lead to buckets optimized for that. But the optimal tree would be the one that minimizes the error of the regression model for the samples in each bucket.

I don't know a simple solution for this. It would be nice if the *criterion* parameter from `sklearn.tree.DecisionTreeRegressor` could be a callable object (a custom function). Otherwise the process of building the tree might have to be done from scratch if this is idea is to be implemented.

IDK if this is related to #35, mentioning just in case.

Thanks for the great repo BTW :-)

**Comment by sdpython** [comment]
Implementing a custom criterion is doable but it has be called from cython if we want to reuse scikit-learn code. I did it once and ended up with the following class: https://github.com/sdpython/mlinsights/blob/master/mlinsights/mlmodel/_piecewise_tree_regression_common.pyx. I did not have time to dedicate some times to go further.

**Comment by m0wer** [comment]
¡That's exactly what I was looking for! Thanks.

I've tried it but surprisingly got worse results than with the `PiecewiseEstimator`.

**Comment by sdpython** [comment]
It took me some times to make it work.
