### ISSUE TITLE
LICENSE file missing in PyPI release

### ISSUE THREAD

**Issue by janjagusch** [sdpython/mlinsights#99]
Hi! 👋 

Thanks for maintaining this package. I'm trying to add `mlinsights` to [conda-forge](https://github.com/conda-forge/staged-recipes/pull/15048) but it turns out to be a bit difficult because the `LICENSE.txt` is not packaged into [mlinsights-0.3.549.tar.gz](https://pypi.org/project/mlinsights/#files).

I think that should be as easy as adjusting the `MANIFEST.in`. I can open a PR for this next week, if that's okay for you. 😄

**Comment by sdpython** [comment]
Thanks, I'll fix this soon.

**Comment by sdpython** [comment]
The package was recently release the license.
